version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:c27e9b1c22713ec5611e77e9acc3a2f7bfa98da85fb931df4db5b2adfb436936
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
